[workspace]
members = ["crates/acpd-core", "crates/acpd-py"]
resolver = "2"
[workspace.package]
version = "0.2.1"
edition = "2021"
rust-version = "1.90"
license = "MIT AND BSD-3-Clause"
[workspace.dependencies]
nalgebra = { version = "=0.34.2", default-features = false, features = ["std"] }
ndarray = "=0.17.2"
numpy = "=0.28.0"
pyo3 = "=0.28.3"
acpd-core = { path = "crates/acpd-core" }
